
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module HW_Interface(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Arduino //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N
);

`define BUFFER_LEN 6
wire [7:0] data [0 : `BUFFER_LEN - 1];

wire reset = ~KEY[0];
reg [7:0] DataOut;
wire DataTrigger;

reg [31:0] index;

`define CLK_BIT 15
reg [24:0] ClockDivider;
always@(posedge ADC_CLK_10) begin
	ClockDivider <= ClockDivider + 1'b1;
end

always@(posedge ClockDivider[`CLK_BIT], posedge reset) begin
	if (reset) begin
		index = 0;
		DataOut = 0;
	end
	else if (index <= `BUFFER_LEN) begin
		DataOut = data[index];
		index = index + 1'b1;
	end
end

generate 
	genvar i;
	for (i = 0; i < `BUFFER_LEN - 1; i = i + 1) begin : FillData
		assign data[i] = "a" + i;
	end
endgenerate
assign data[5] = "\n";
// assign data[0] = "a";
// assign data[1] = "b";
// assign data[2] = "c";
// assign data[3] = "d";
// assign data[4] = "e";

assign DataTrigger = (index <= `BUFFER_LEN) ? reset | ~ClockDivider[`CLK_BIT] : 1'b0;
assign ARDUINO_IO[7:0] = DataOut;
assign ARDUINO_IO[8] = DataTrigger;

assign ARDUINO_RESET_N = 1'b1;

endmodule

